language: android

jdk:
 - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.3
    - android-24
    - extra-android-m2repository
    - extra-google-m2repository

script:
  - ./gradlew assembleDebug
  - ls -l app/build/outputs/apk/

cache:
  directories:
    - $HOME/.gradle